# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Fallenstedt
email: a.fallenstedt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Junior Web Developer, photographer, and graduate of Biology. Alex combines his eye for design and photography with his web development skills to produce responsive websites with the user in mind.
baseurl: "" # the subpath of your site, e.g. /blog
url: "fallenstedt.github.io" # the base hostname & protocol for your site
twitter_username: fallenstedt
github_username:  Fallenstedt
fivehundred_username: alexanderfallenstedt
linkedin_username: alexfallenstedt

# Build settings
markdown: kramdown
theme: minima

collections:
  sass:
    sass_dir: _sass
  includes:
    includes_dir: _includes
  js:
    js_dir: _js
  images:
    images_dir: _images
  timeline:
    timeline_dir: _timeline
  portfolios:
    portfolios_dir: _portfolios
    output: true
    permalink: /:collection/:title/
  codes:
    codes_dir: _code
    output: true
    permalink: /:collection/:title/
gems:
  - jekyll-livereload
